spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: ${ACTIVITY_DB_URI:mongodb://activityservice:activityservice@localhost:27017/fitness_activity_db?authSource=admin}
      database: fitness_activity_db

server:
  port: ${ACTIVITY_SERVICE_PORT:8082}