spring:
  application:
    name: ai-service
server:
  port: ${ACTIVITY_SERVICE_PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/