services:
  mongodb:
    image: mongo:7
    container_name: activityservice-mongodb
    environment:
      MONGO_INITDB_DATABASE: fitness_activity_db
      MONGO_INITDB_ROOT_USERNAME: activityservice
      MONGO_INITDB_ROOT_PASSWORD: activityservice
    ports:
      - "27017:27017"
    volumes:
      - activityservice-mongodb-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  activityservice-mongodb-data:
